### ISSUE TITLE
Windows Installer: Rebooting/Closing of Applications (eg. Explorer, OneNote) required

### ISSUE THREAD

**Issue by Velocet** [Ultraschall/REAPER#13]
Bei der Installation merkt der Installer an das z.B. die beiden genannten Apps geschlossen werden sollen. In Office wird nichts geändert bzw. nichts installiert und im Explorer wird auch nichts geändert. Scheinbar beendet der Installer auch die Explorer.exe und startet diese neu was nicht notwendig ist.

**Comment by heikopanjas** [comment]
Welche Windows- und Office-Versionen sind das?

**Comment by heikopanjas** [comment]
The author doesn't seem to care anymore. Closed.
