### ISSUE TITLE
Installer/Anleitung: Ultraschall_2.2.ReaperConfigZip nicht auf Desktop

### ISSUE THREAD

**Issue by Velocet** [Ultraschall/REAPER#14]
Die in der [Anleitung unter Punkt 3](http://ultraschall.fm/install-notes/) genannte Datei _Ultraschall_2.2.ReaperConfigZip_ befindet sich nicht auf Desktop sondern im Ultraschall Verzeichnis.
Entweder ein Problem des Installer oder die Anleitung ist in diesem Punkt falsch.

**Comment by rstockm** [comment]
Da steht: "REAPER starten und die nun auf dem Desktop zu findende Datei Ultraschall `REAPER Theme` in das geöffnete REAPER-Fenster fallen lassen" - und die Datei gibt es als Verknüpfung auf dem Desktop?

**Comment by heikopanjas** [comment]
I'm closing this as there is no response for three weeks now.

**Comment by djungowski** [comment]
Ich kann bestätigen, dass die Datei `Ultraschall REAPER Theme` nicht auf dem Desktop zu finden war

**Comment by heikopanjas** [comment]
Do you refer to the current ULTRASCHALL release (3.0.3) or to the version that had the original problem? Which OS were you using when you ran into the problem. Windows? Please tell us about your system: 7, 8 or 10? Pro or Home? x86 or x64? English or German? Which kind of user were you running when you tried to install ULTRASCHALL?

**Comment by djungowski** [comment]
So, this is what I used:
- Reaper 5.40 (reaper540_x64-install.exe)
- Ultraschall 3.0.3 (Ultraschall-3.0.3.msi)
- Windows 10 Home 64 Bit, German
- According to system control, the user I was installing it with is an Administrator
